//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loader.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на import os
        ///
        ///# This can also be replaced with another IP address.
        ///USE_SSL = True
        ///REMOTE_HOST = &quot;REPLACEHEREIP&quot;
        ///REMOTE_PORT = REPLACEHEREPORT
        ///
        ///if os.getenv(&apos;MITM_REMOTE_HOST&apos;) != None:
        ///    REMOTE_HOST = os.getenv(&apos;MITM_REMOTE_HOST&apos;)
        ///if os.getenv(&apos;MITM_REMOTE_PORT&apos;) != None:
        ///    REMOTE_PORT = int(os.getenv(&apos;MITM_REMOTE_PORT&apos;))
        ///if os.getenv(&apos;MITM_USE_SSL&apos;) != None:
        ///    USE_SSL = bool(os.getenv(&apos;MITM_USE_SSL&apos;))
        ///
        ///print(&apos;MITM Remote Host: &apos; + REMOTE_HOST)
        ///print(&apos;MITM Remote Port: &apos; + str(REMOTE_PORT) [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string config_proxy_py {
            get {
                return ResourceManager.GetString("config_proxy.py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /* Original script by NicknameGG, modified for VincDev For GenshinPSID. */
        ///import System;
        ///import System.Windows.Forms;
        ///import Fiddler;
        ///import System.Text.RegularExpressions;
        /// 
        ///class Handlers
        ///{
        ///    static function OnBeforeRequest(oS: Session) {
        ///        if(oS.host.EndsWith(&quot;.yuanshen.com&quot;) || oS.host.EndsWith(&quot;.hoyoverse.com&quot;) || oS.host.EndsWith(&quot;.mihoyo.com&quot;)) {
        ///            oS.host = &quot;SCRPTIPREPLACER&quot;; // This can also be replaced with another IP address .
        ///        }
        ///    }
        ///};.
        /// </summary>
        public static string FiddlerScript {
            get {
                return ResourceManager.GetString("FiddlerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##
        ///#
        ///#   Copyright (C) 2002-2022 MlgmXyysd All Rights Reserved.
        ///#
        ///##
        ///
        ///##
        ///#
        ///#   Animation Company script for mitmproxy
        ///#
        ///#   https://github.com/MlgmXyysd/
        ///#
        ///#   *Original fiddler script from https://github.lunatic.moe/fiddlerscript
        ///#
        ///#   Environment requirement:
        ///#     - mitmdump from mitmproxy
        ///#
        ///#   @author MlgmXyysd
        ///#   @version 1.1
        ///#
        ///##
        ///
        ///import collections
        ///import random
        ///from mitmproxy import http, connection, ctx, tls
        ///from abc import ABC, abstractmethod
        ///from enum import Enum
        ///from [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string proxy_py {
            get {
                return ResourceManager.GetString("proxy.py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Settings]
        ///genshinclients=0
        ///grasscuters=0
        ///metshod=fiddler.
        /// </summary>
        public static string StandartConfig {
            get {
                return ResourceManager.GetString("StandartConfig", resourceCulture);
            }
        }
    }
}
