//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loader.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на import os
        ///
        ///# This can also be replaced with another IP address.
        ///USE_SSL = True
        ///REMOTE_HOST = &quot;REPLACEHEREIP&quot;
        ///REMOTE_PORT = REPLACEHEREPORT
        ///
        ///if os.getenv(&apos;MITM_REMOTE_HOST&apos;) != None:
        ///    REMOTE_HOST = os.getenv(&apos;MITM_REMOTE_HOST&apos;)
        ///if os.getenv(&apos;MITM_REMOTE_PORT&apos;) != None:
        ///    REMOTE_PORT = int(os.getenv(&apos;MITM_REMOTE_PORT&apos;))
        ///if os.getenv(&apos;MITM_USE_SSL&apos;) != None:
        ///    USE_SSL = bool(os.getenv(&apos;MITM_USE_SSL&apos;))
        ///
        ///print(&apos;MITM Remote Host: &apos; + REMOTE_HOST)
        ///print(&apos;MITM Remote Port: &apos; + str(REMOTE_PORT) [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string config_proxy_py {
            get {
                return ResourceManager.GetString("config_proxy.py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;AMW28dptX3h8q0O4z/vJrQxf6cmC6yVilgHRL98GazrYzmc3ixj87JpHIJ3IKEYV+HU/tYrUjEfY/ZtPzsLB9lKBelN9i8QjkFkA9QDICGYwJCXibxU67Z/HzENe9NQpG2i01SI0TJU8PJDV7zQPwPVGraIg5ouExRupq8UymaSHEyJ7zxKZCtgO0LKdROLJBSvI5srMu7kYTGmB7T07Ab8T9M595YSgd1vh06qZ3nsF1h4wg3y+zW28vdY28+RCj2V1i7oVyL0dQruLYq7qK8FycZl2j9R0GaJ8rRAjVP1Dsz+hjS3atHhQxOG9OFo6d/euedRvfWIhT9p6h1SeTjE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        public static string dispatcherKey {
            get {
                return ResourceManager.GetString("dispatcherKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /* Original script by NicknameGG, modified for VincDev For GenshinPSID. */
        ///import System;
        ///import System.Windows.Forms;
        ///import Fiddler;
        ///import System.Text.RegularExpressions;
        /// 
        ///class Handlers
        ///{
        ///    static function OnBeforeRequest(oS: Session) {
        ///        if(oS.host.EndsWith(&quot;.yuanshen.com&quot;) || oS.host.EndsWith(&quot;.hoyoverse.com&quot;) || oS.host.EndsWith(&quot;.mihoyo.com&quot;)) {
        ///            oS.host = &quot;SCRPTIPREPLACER&quot;; // This can also be replaced with another IP address .
        ///        }
        ///    }
        ///};.
        /// </summary>
        public static string FiddlerScript {
            get {
                return ResourceManager.GetString("FiddlerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_close_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_close_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_close_96px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_close_96px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_download_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_download_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_folder_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_folder_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_github_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_github_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_minus_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_minus_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_plus_math_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_plus_math_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_settings_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_settings_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] metadata_extractor {
            get {
                object obj = ResourceManager.GetObject("metadata_extractor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;
        ///                                                &lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///                                                &lt;Modulus&gt;yytg/H9lz7Lm0XcA8LMqIyXPVNApYTcSepT4VDLB4qqqFC3s
        ///                                                /Huv8vN7zA/P4uoREIu8KMenADFk7uwrZSxoMWwJgn6A7sbAt1cqAaUXB
        ///                                                9J4NzhL0x3AFTiHEQbw86hRvm2VGkbA5sWnr0NZw8SGBBY+EODwNIt51G
        ///                                                dBA7eoUQU=&lt;/Modulus&gt;
        ///                                [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string passwordKey {
            get {
                return ResourceManager.GetString("passwordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##
        ///#
        ///#   Copyright (C) 2002-2022 MlgmXyysd All Rights Reserved.
        ///#
        ///##
        ///
        ///##
        ///#
        ///#   Animation Company script for mitmproxy
        ///#
        ///#   https://github.com/MlgmXyysd/
        ///#
        ///#   *Original fiddler script from https://github.lunatic.moe/fiddlerscript
        ///#
        ///#   Environment requirement:
        ///#     - mitmdump from mitmproxy
        ///#
        ///#   @author MlgmXyysd
        ///#   @version 1.1
        ///#
        ///##
        ///
        ///import collections
        ///import random
        ///from mitmproxy import http, connection, ctx, tls
        ///from abc import ABC, abstractmethod
        ///from enum import Enum
        ///from [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string proxy_py {
            get {
                return ResourceManager.GetString("proxy.py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Raiden_Shogun_Build_Guide_For_Genshin_Impact {
            get {
                object obj = ResourceManager.GetObject("Raiden-Shogun-Build-Guide-For-Genshin-Impact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Settings]
        ///genshinclients=0
        ///grasscuters=0
        ///backimg=https://cdn.discordapp.com/attachments/884137212696989756/1000835575147937852/Ayato.png.
        /// </summary>
        public static string StandartConfig {
            get {
                return ResourceManager.GetString("StandartConfig", resourceCulture);
            }
        }
    }
}
